#!/usr/bin/env python3
"""Compile stimulus.{vert,frag} to SPIR-V, embed as uint32 arrays in StimulusShadersSpv.h.

Requires glslangValidator on PATH. Run from the project root:
    python3 scripts/embed_shaders.py
"""
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHADER_DIR = ROOT / "app/src/main/cpp/renderer/shaders"
HEADER_OUT = ROOT / "app/src/main/cpp/renderer/StimulusShadersSpv.h"


def compile_glsl(src: Path, out: Path) -> None:
    r = subprocess.run(
        ["glslangValidator", "-V", str(src), "-o", str(out)],
        capture_output=True, text=True
    )
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        sys.exit(f"glslang failed for {src}")


def to_uint32_array(spv: Path) -> tuple:
    data = spv.read_bytes()
    assert len(data) % 4 == 0
    return struct.unpack(f"<{len(data)//4}I", data)


def emit(name: str, words: tuple) -> str:
    lines = [f"static const uint32_t {name}[] = {{"]
    for i in range(0, len(words), 6):
        lines.append("    " + ", ".join(f"0x{w:08x}u" for w in words[i:i+6]) + ",")
    lines.append("};")
    lines.append(f"static const size_t {name}_size = sizeof({name});")
    return "\n".join(lines)


def main() -> int:
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        vert_spv = td / "stimulus.vert.spv"
        frag_spv = td / "stimulus.frag.spv"
        compile_glsl(SHADER_DIR / "stimulus.vert", vert_spv)
        compile_glsl(SHADER_DIR / "stimulus.frag", frag_spv)
        vert = to_uint32_array(vert_spv)
        frag = to_uint32_array(frag_spv)
    hdr = "// Auto-generated by scripts/embed_shaders.py; do not hand-edit.\n"
    hdr += "// Source: app/src/main/cpp/renderer/shaders/stimulus.{vert,frag}\n"
    hdr += "#pragma once\n#include <cstdint>\n#include <cstddef>\n\nnamespace rsp::shaders {\n\n"
    hdr += emit("kStimulusVertSpv", vert) + "\n\n"
    hdr += emit("kStimulusFragSpv", frag) + "\n\n"
    hdr += "}  // namespace rsp::shaders\n"
    HEADER_OUT.write_text(hdr)
    print(f"wrote {HEADER_OUT} (vert={len(vert)} words, frag={len(frag)} words)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
